.TH FCITX 1 "November 19, 2010"

.SH NAME
fcitx \- Free Chinese Input Toy for X (XIM)
.SH SYNOPSIS
.B fcitx
.br
.SH DESCRIPTION
\fBfcitx\fP is a small and fast input server initially designed for Chinese, 
 which is also useful for some other languages (especially CJK) now. 
.SH SEE ALSO
.BR /usr/share/doc/fcitx/fcitx4.pdf.gz ,
.br
.SH AUTHOR
fcitx was written by Yuking <yuking_net@sina.com> and CSSplayer <wengxt@gmail.com>.
.PP
This manual page was written by Aron Xu <happyaron.xu@gmail.com>,
for the Debian project (and may be used by others).
